{
      "bahasa": "Silahkan pilih bahasa untuk melihat list bahasa silahkan tekan button dibawah ini",
      "maxtext": "Maksimal 150 text kakak",
      "sukses1": "Sukses, pesan anda telah saya sampaikan kepada owner",
      "sukses2": "Sukses broadcast",
      "sukses3": "Berhasil",
      "errory": "Error, Silahkan coba lagi",
      "rplysend": "Nih kakak",
      "tbk": "TEBAK INI APA, WAKTU 30 DETIK",
      "tbk2": "[❗] WAKTU 30 DETIK",
      "nourl": "Masukkan url",      
      "replybiasater": "Hehhh.. Seperti biasa... yang",
      "replyin": "Disini",
      "terreply": "Jadi gini bro, gw tuh yg ter",
      "notfitur": "sepertinya tidak terdaftar di dalam menu bot, silahkan cek menu kembali:)",
      "respon": "Yahh kakak? Saya di sini, ada yang bisa saya bantu?",
      "botadmin": "maaf fitur ini hanya bisa digunakan jika bot menjadi admin",           
      "group": "maaf fitur ini hanya bisa digunakan di group",           
      "admin": "maaf fitur ini hanya bisa digunakan oleh admin group",
      "owner": "maaf fitur ini hanya bisa digunakan oleh owner bot",
      "member": "maaf fitur ini hanya bisa digunakan oleh member group",
      "pribadi": "maaf fitur ini hanya bisa digunakan dipesan pribadi",
      "premium": "maaf fitur ini hanya bisa digunakan user premium",
      "linkerror": "Link yang anda kirimkan error",
      "nolink": "Masukkan link grub",
      "reptag": "Tag orang kak:)",
      "banned": "Maaf tapi anda telah terbanned:(",
      "fakeaudio": "Nihh audio nya kakak:)",
      "nonumber": "Masukkan nomer, note : jangan beri spasi/kode(+-) pada nomer",
      "nocode": "Masukkan kode negara",
      "timetag": "Pesan anda akan terkirim pada",
      "kikrndm": "Mencari member random di grub ini",
      "noprefix": "Masukkan prefix baru, maksimal 1 angka/huruf",                        
      "notext": "Masukkan text nya kakak",     
      "minat": "\nJIKA MINAT SILAHKAHKAN HUBUNGI OWNER",
      "pilihiklan": "\nJIKA MINAT SILAHKAHKAN HUBUNGI OWNER",
      "noselesai": "SELESEIN YG SEBELUMNYA TERLEBIH DAHULU",
	  "bocoran": "PERMAINKAN GAMES sSEDANG BERLANGSUNG DENGAN BOCORAN JAWABAN : ",
	  "tebak30": "\nJAWAB TEBAKAN INI, JAWABAN YANG BENAR AKAN SAYA REPLY, WAKTU UNTUK MENJAWAB 30 DETIK",
	  "nowaktu": "WAKTU HABIS!!\nJAWABAN : ", 
      "nostick": "NYA APA? SILAHKAN TEKAN BUTTON DI BAWAH INI:)",
      "nostickk": "TIDAK DI TEMUKAN! SILAHKAN TEKAN BUTTON DI BAWAH INI:)",
      "nostick1": "REPLY STIKER NYA",
      "novn1": "REPLY VN NYA",
      "noimg1": "REPLY IMAGE NYA",
      "novideo1": "REPLY VIDEO NYA",
      "nostickkkk": "NAMA STICKER NYA APA?",
      "liststick": "SILAHKAN TEKAN BUTTON DI BAWAH INI:)",
      "stz": "Silahkan pilih salah satu tz di bawah"
}